### ISSUE TITLE
Quick Settings - Unity8 - untranslated - German

### ISSUE THREAD

**Issue by openlewa** [ubports/indicator-keyboard#19]
Please Fix. Thank you in advance.
![20200617_203354](https://user-images.githubusercontent.com/54738746/85210860-d5d66600-b343-11ea-9101-550e7df63d9d.jpg)

Keyboard Layout = Tastatur Layout
Text Entry Settings = Tastaturbelegungen

**Comment by Flohack74** [comment]
Transferred to indicator keyboard. Please lets check for correct localizations in the code.

**Comment by Flohack74** [comment]
Hopefully fixed in #22
