### ISSUE TITLE
Update translations?

### ISSUE THREAD

**Issue by cibersheep** [ubports/indicator-keyboard#5]
Even if the translation are in the repo, some text are not translated in the final image. Does it need to update or include in the final image?

Xenial RC and Xenial Dev 669

![imatge](https://user-images.githubusercontent.com/6640041/47583729-9847ec80-d958-11e8-820d-efc4895bd3c4.png)

**Comment by Flohack74** [comment]
This is similar to #8 :) Let me check if I can recreate the pot file...

**Comment by cibersheep** [comment]
Oh, it's a duplicate in «the full rule». 

Closed: duplicate #8

**Comment by cibersheep** [comment]
Ok :) close reopen... sorry. Only one must stay for now

**Comment by Flohack74** [comment]
Done with #22 hopefully ^^
